In [1]:
import numpy as np
import pandas as pd

In [2]:
s2019 = pd.read_excel("/content/Bangalore Schools 2019.xlsx")
s2020 = pd.read_excel('/content/Bangalore Schools 2020.xlsx')
s2021 = pd.read_excel('/content/Bangalore Schools 2021.xlsx')

In [3]:
s2019.columns

Index(['Student Roll', 'Student Name', 'Hindi', 'English', 'Mathematics',
       'Physics', 'Chemistry', 'Biology', 'History', 'Geography', 'Civics',
       'Computer Science', 'Physical Education'],
      dtype='object')

In [4]:
s2019.head()

,Student Roll,Student Name,Hindi,English,Mathematics,Physics,Chemistry,Biology,History,Geography,Civics,Computer Science,Physical Education
0,1001,Akash Ahuja,30,95,78,92,84,36,47,82,44,14,74
1,1002,Mohit Srivatsav,32,46,65,53,28,77,36,76,74,77,27
2,1003,Anshika Mehra,87,91,74,81,88,100,45,37,10,44,11
3,1004,Visakha Tamboli,65,83,83,78,45,61,16,89,52,23,50
4,1005,Raju Deshmukh,84,66,98,62,68,99,70,61,65,75,87

In [5]:
s2020.columns

Index(['Student Roll', 'Student Name', 'Hindi', 'English', 'Mathematics',
       'Physics', 'Chemistry', 'Biology', 'History', 'Geography', 'Civics',
       'Computer Science', 'Physical Education'],
      dtype='object')

In [6]:
s2020.head()

,Student Roll,Student Name,Hindi,English,Mathematics,Physics,Chemistry,Biology,History,Geography,Civics,Computer Science,Physical Education
0,1001,Akash Ahuja,39,74,87,92,84,36,47,82,44,81,78
1,1002,Mohit Srivatsav,72,38,97,53,28,77,36,76,74,68,81
2,1003,Anshika Mehra,82,52,94,81,88,100,45,37,10,36,69
3,1004,Visakha Tamboli,44,68,62,78,45,61,16,89,52,37,45
4,1005,Raju Deshmukh,83,49,44,62,68,99,70,61,65,82,39

In [7]:
s2021.columns

Index(['Student Roll', 'Student Name', 'Hindi', 'English', 'Mathematics',
       'Physics', 'Chemistry', 'Biology', 'History', 'Geography', 'Civics',
       'Computer Science', 'Physical Education'],
      dtype='object')

In [8]:
s2021.head()

,Student Roll,Student Name,Hindi,English,Mathematics,Physics,Chemistry,Biology,History,Geography,Civics,Computer Science,Physical Education
0,1001,Akash Ahuja,55,63,93,66,59,20,84,61,55,63,80
1,1002,Mohit Srivatsav,64,62,53,69,81,35,35,67,44,72,78
2,1003,Anshika Mehra,89,64,53,51,80,52,83,22,53,94,49
3,1004,Visakha Tamboli,67,61,52,54,21,30,23,23,61,78,46
4,1005,Raju Deshmukh,68,97,62,78,80,25,71,74,74,62,50

1.Reward the top performer (student) of each school based on cumulative marks scored in last three years for all the subjects

In [4]:

files = {
    2019: '/content/Bangalore Schools 2019.xlsx',
    2020: '/content/Bangalore Schools 2020.xlsx',
    2021: '/content/Bangalore Schools 2021.xlsx',
}

data = []
for year, file_path in files.items():
    df = pd.read_excel(file_path)
    df.columns = df.columns.str.strip().str.lower()
    df['year'] = year
    data.append(df)

combined_data = pd.concat(data, ignore_index=True)

combined_data['total_marks'] = combined_data.iloc[:, 2:].sum(axis=1)

cumulative_marks = (
    combined_data.groupby(['student roll', 'student name'], as_index=False)
    .agg({'total_marks': 'sum'})
)

top_performer = cumulative_marks.loc[cumulative_marks['total_marks'].idxmax()]

print("Top Performer Over the Last Three Years:")
print(top_performer)

Top Performer Over the Last Three Years:
student roll            1020
student name    Nisha Saxena
total_marks             8380
Name: 19, dtype: object

2.Rank each student within their own school based on their total marks scored in the year 2020 and compare the marks of Rank 10 for each school by arranging them in descending order

In [5]:
s2020.columns = s2020.columns.str.strip().str.lower()

s2020['total_marks'] = s2020.iloc[:, 2:].sum(axis=1)

s2020['rank'] = s2020['total_marks'].rank(method='min', ascending=False)

rank_10_student = s2020[s2020['rank'] == 10]

ranked_students_sorted = s2020.sort_values(by='total_marks', ascending=False)

print("10th Ranked Student(s):")
print(rank_10_student[['student name', 'total_marks']])
print("\nTop Students Sorted by Total Marks:")
print(ranked_students_sorted[['student name', 'total_marks']].head(15))

10th Ranked Student(s):
     student name  total_marks
11  Ganesh Sekhar          705

Top Students Sorted by Total Marks:
            student name  total_marks
14           Raheem Khan          759
19          Nisha Saxena          752
0            Akash Ahuja          744
16          Rashmi Desai          726
4          Raju Deshmukh          722
12         Praddep Meena          720
7         Anamika Kumari          718
5             Aruna Iyer          716
17  Sanjana Venkatramana          711
11         Ganesh Sekhar          705
1        Mohit Srivatsav          700
2          Anshika Mehra          694
18        Gurpreet Singh          662
15             Md. Yusuf          644
8           Piyush Pande          644

3.Find out students with the highest improvement for each subject from 2019-21 combining all the schools together

In [6]:
data = {}
for year, file_path in files.items():
    df = pd.read_excel(file_path)
    df.columns = df.columns.str.strip().str.lower()
    df['year'] = year
    data[year] = df

data_2019 = data[2019].set_index('student roll')
data_2021 = data[2021].set_index('student roll')

common_columns = list(set(data_2019.columns) & set(data_2021.columns))

numeric_columns = [col for col in common_columns if data_2019[col].dtype != object and data_2021[col].dtype != object]


improvement = data_2021[numeric_columns].subtract(data_2019[numeric_columns], fill_value=0)

improvement['student name'] = data_2019['student name']

top_improvers = {}
for subject in numeric_columns:
    if subject not in ['student name', 'year']:
        top_student = improvement[subject].idxmax()
        top_improvers[subject] = {
            'student roll': top_student,
            'student name': improvement.loc[top_student, 'student name'],
            'improvement': improvement.loc[top_student, subject],
        }

print("Students with the Highest Improvement for Each Subject (2019-2021):")
for subject, details in top_improvers.items():
    print(f"{subject.capitalize()}: {details}")

Students with the Highest Improvement for Each Subject (2019-2021):
Civics: {'student roll': 1018, 'student name': 'Sanjana Venkatramana', 'improvement': 65}
Physical education: {'student roll': 1008, 'student name': 'Anamika Kumari', 'improvement': 58}
Geography: {'student roll': 1010, 'student name': 'Subhajeet Dutta', 'improvement': 61}
English: {'student roll': 1010, 'student name': 'Subhajeet Dutta', 'improvement': 51}
Chemistry: {'student roll': 1002, 'student name': 'Mohit Srivatsav', 'improvement': 53}
History: {'student roll': 1014, 'student name': 'Albert Pinto', 'improvement': 45}
Mathematics: {'student roll': 1016, 'student name': 'Md. Yusuf', 'improvement': 38}
Hindi: {'student roll': 1011, 'student name': 'Sonal Tripathi', 'improvement': 71}
Biology: {'student roll': 1011, 'student name': 'Sonal Tripathi', 'improvement': 36}
Computer science: {'student roll': 1017, 'student name': 'Rashmi Desai', 'improvement': 82}
Physics: {'student roll': 1013, 'student name': 'Praddep Meena', 'improvement': 63}

4.Identify best school for Arts, Science and Commerce streams based on marks scored by students in respective subjects for those streams in last three years

In [9]:
file_paths = {
    "2021": "/content/Bangalore Schools 2021.xlsx",
    "2020": "/content/Bangalore Schools 2020.xlsx",
    "2019": "/content/Bangalore Schools 2019.xlsx",
}

def compute_stream_averages(data):
    arts_subjects = ['History', 'Geography', 'Civics']
    science_subjects = ['Mathematics', 'Physics', 'Chemistry', 'Biology']
    commerce_subjects = ['Computer Science']

    arts_avg = data[arts_subjects].mean(axis=1).mean() if all(sub in data for sub in arts_subjects) else None
    science_avg = data[science_subjects].mean(axis=1).mean() if all(sub in data for sub in science_subjects) else None
    commerce_avg = data[commerce_subjects].mean(axis=1).mean() if all(sub in data for sub in commerce_subjects) else None

    return {"Arts": arts_avg, "Science": science_avg, "Commerce": commerce_avg}

# Aggregate results for all years
results = {}
for year, path in file_paths.items():
    year_data = pd.ExcelFile(path)
    year_results = {}
    for sheet in year_data.sheet_names:
        school_data = pd.read_excel(year_data, sheet_name=sheet)
        year_results[sheet] = compute_stream_averages(school_data)
    results[year] = year_results

# Print the results for each year
for year, schools in results.items():
    print(f"Year: {year}")
    for school, averages in schools.items():
        print(f"  {school}:")
        for stream, avg in averages.items():
            print(f"    {stream}: {avg:.2f}" if avg is not None else f"    {stream}: No data")
    print("\n")

Year: 2021
  Vidya Mandir:
    Arts: 55.07
    Science: 57.44
    Commerce: 76.00
  St. Joseph:
    Arts: 54.88
    Science: 54.05
    Commerce: 47.65
  DPS:
    Arts: 56.95
    Science: 55.36
    Commerce: 53.55
  Birla HS:
    Arts: 69.73
    Science: 52.54
    Commerce: 47.65
  International:
    Arts: 50.90
    Science: 69.51
    Commerce: 71.60


Year: 2020
  Vidya Mandir:
    Arts: 54.75
    Science: 66.10
    Commerce: 64.95
  St. Joseph:
    Arts: 54.03
    Science: 57.17
    Commerce: 56.20
  DPS:
    Arts: 57.62
    Science: 53.48
    Commerce: 54.75
  Birla HS:
    Arts: 72.22
    Science: 55.36
    Commerce: 60.05
  International:
    Arts: 53.08
    Science: 67.08
    Commerce: 69.50


Year: 2019
  Vidya Mandir:
    Arts: 54.75
    Science: 67.40
    Commerce: 48.15
  St. Joseph:
    Arts: 57.35
    Science: 61.49
    Commerce: 60.20
  DPS:
    Arts: 64.88
    Science: 56.83
    Commerce: 67.65
  Birla HS:
    Arts: 68.68
    Science: 58.40
    Commerce: 53.95
  International:
    Arts: 49.32
    Science: 72.36
    Commerce: 72.80

5. If the marks obtained for each subject can be categorised under 5 sections like below:
    
          <=20 - Very Poor
    
    >20 - <=40 - Poor
    
    >40 - <=60 - Average
    
    >60 - <=80 - Good
    
    >80 - <=100 - Very Good
    

Then calculate for each school how many students were in each category based on the avg. marks obtained each year

In [10]:


# Function to compute average marks per stream for a given dataset
def compute_stream_averages(data):
    arts_subjects = ['History', 'Geography', 'Civics']
    science_subjects = ['Mathematics', 'Physics', 'Chemistry', 'Biology']
    commerce_subjects = ['Computer Science']

    arts_avg = data[arts_subjects].mean(axis=1).mean() if all(sub in data for sub in arts_subjects) else None
    science_avg = data[science_subjects].mean(axis=1).mean() if all(sub in data for sub in science_subjects) else None
    commerce_avg = data[commerce_subjects].mean(axis=1).mean() if all(sub in data for sub in commerce_subjects) else None

    return {"Arts": arts_avg, "Science": science_avg, "Commerce": commerce_avg}

# Function to categorize students based on their average marks
def categorize_students(data):
    categories = {
        "Very Poor": (0, 20),
        "Poor": (21, 40),
        "Average": (41, 60),
        "Good": (61, 80),
        "Very Good": (81, 100)
    }

    avg_marks = data.mean(axis=1)
    category_counts = {category: 0 for category in categories}

    for mark in avg_marks:
        for category, (low, high) in categories.items():
            if low <= mark <= high:
                category_counts[category] += 1
                break

    return category_counts

# Aggregate results for all years
results = {}
category_results = {}

for year, path in file_paths.items():
    year_data = pd.ExcelFile(path)
    year_results = {}
    year_category_results = {}

    for sheet in year_data.sheet_names:
        school_data = pd.read_excel(year_data, sheet_name=sheet)
        year_results[sheet] = compute_stream_averages(school_data)
        year_category_results[sheet] = categorize_students(school_data.iloc[:, 2:])  # Exclude non-subject columns

    results[year] = year_results
    category_results[year] = year_category_results

# Print the results for each year
for year, schools in results.items():
    print(f"Year: {year}")
    for school, averages in schools.items():
        print(f"  {school}:")
        for stream, avg in averages.items():
            print(f"    {stream}: {avg:.2f}" if avg is not None else f"    {stream}: No data")
    print("\n")

# Print the category distribution for each year
for year, schools in category_results.items():
    print(f"Year: {year} - Category Distribution")
    for school, categories in schools.items():
        print(f"  {school}:")
        for category, count in categories.items():
            print(f"    {category}: {count}")
    print("\n")

Year: 2021
  Vidya Mandir:
    Arts: 55.07
    Science: 57.44
    Commerce: 76.00
  St. Joseph:
    Arts: 54.88
    Science: 54.05
    Commerce: 47.65
  DPS:
    Arts: 56.95
    Science: 55.36
    Commerce: 53.55
  Birla HS:
    Arts: 69.73
    Science: 52.54
    Commerce: 47.65
  International:
    Arts: 50.90
    Science: 69.51
    Commerce: 71.60


Year: 2020
  Vidya Mandir:
    Arts: 54.75
    Science: 66.10
    Commerce: 64.95
  St. Joseph:
    Arts: 54.03
    Science: 57.17
    Commerce: 56.20
  DPS:
    Arts: 57.62
    Science: 53.48
    Commerce: 54.75
  Birla HS:
    Arts: 72.22
    Science: 55.36
    Commerce: 60.05
  International:
    Arts: 53.08
    Science: 67.08
    Commerce: 69.50


Year: 2019
  Vidya Mandir:
    Arts: 54.75
    Science: 67.40
    Commerce: 48.15
  St. Joseph:
    Arts: 57.35
    Science: 61.49
    Commerce: 60.20
  DPS:
    Arts: 64.88
    Science: 56.83
    Commerce: 67.65
  Birla HS:
    Arts: 68.68
    Science: 58.40
    Commerce: 53.95
  International:
    Arts: 49.32
    Science: 72.36
    Commerce: 72.80


Year: 2021 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 7
    Good: 11
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 18
    Good: 2
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 14
    Good: 4
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 9
    Good: 8
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 10
    Very Good: 0


Year: 2020 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 7
    Good: 12
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 14
    Good: 6
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 19
    Good: 1
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 6
    Good: 10
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 11
    Good: 8
    Very Good: 0


Year: 2019 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 10
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 11
    Good: 9
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 12
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 5
    Good: 14
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 6
    Good: 14
    Very Good: 0

6.Which is the best school for each year 2019, 2020 and 2021 based on highest no. of students in Good and Very Good category

In [11]:


# Function to compute average marks per stream for a given dataset
def compute_stream_averages(data):
    arts_subjects = ['History', 'Geography', 'Civics']
    science_subjects = ['Mathematics', 'Physics', 'Chemistry', 'Biology']
    commerce_subjects = ['Computer Science']

    arts_avg = data[arts_subjects].mean(axis=1).mean() if all(sub in data for sub in arts_subjects) else None
    science_avg = data[science_subjects].mean(axis=1).mean() if all(sub in data for sub in science_subjects) else None
    commerce_avg = data[commerce_subjects].mean(axis=1).mean() if all(sub in data for sub in commerce_subjects) else None

    return {"Arts": arts_avg, "Science": science_avg, "Commerce": commerce_avg}

# Function to categorize students based on their average marks
def categorize_students(data):
    categories = {
        "Very Poor": (0, 20),
        "Poor": (21, 40),
        "Average": (41, 60),
        "Good": (61, 80),
        "Very Good": (81, 100)
    }

    avg_marks = data.mean(axis=1)
    category_counts = {category: 0 for category in categories}

    for mark in avg_marks:
        for category, (low, high) in categories.items():
            if low <= mark <= high:
                category_counts[category] += 1
                break

    return category_counts

# Aggregate results for all years
results = {}
category_results = {}

for year, path in file_paths.items():
    year_data = pd.ExcelFile(path)
    year_results = {}
    year_category_results = {}

    for sheet in year_data.sheet_names:
        school_data = pd.read_excel(year_data, sheet_name=sheet)
        year_results[sheet] = compute_stream_averages(school_data)
        year_category_results[sheet] = categorize_students(school_data.iloc[:, 2:])  # Exclude non-subject columns

    results[year] = year_results
    category_results[year] = year_category_results

# Print the results for each year
for year, schools in results.items():
    print(f"Year: {year}")
    for school, averages in schools.items():
        print(f"  {school}:")
        for stream, avg in averages.items():
            print(f"    {stream}: {avg:.2f}" if avg is not None else f"    {stream}: No data")
    print("\n")

# Print the category distribution for each year
for year, schools in category_results.items():
    print(f"Year: {year} - Category Distribution")
    for school, categories in schools.items():
        print(f"  {school}:")
        for category, count in categories.items():
            print(f"    {category}: {count}")
    print("\n")

# Determine the best school for each year based on Good and Very Good categories
best_schools = {}

for year, schools in category_results.items():
    best_school = None
    max_good_very_good = 0

    for school, categories in schools.items():
        good_very_good_total = categories.get("Good", 0) + categories.get("Very Good", 0)

        if good_very_good_total > max_good_very_good:
            best_school = school
            max_good_very_good = good_very_good_total

    best_schools[year] = (best_school, max_good_very_good)

# Print the best school for each year
print("Best Schools by Year based on Good and Very Good categories:")
for year, (school, count) in best_schools.items():
    print(f"Year {year}: {school} with {count} students in Good and Very Good categories")

Year: 2021
  Vidya Mandir:
    Arts: 55.07
    Science: 57.44
    Commerce: 76.00
  St. Joseph:
    Arts: 54.88
    Science: 54.05
    Commerce: 47.65
  DPS:
    Arts: 56.95
    Science: 55.36
    Commerce: 53.55
  Birla HS:
    Arts: 69.73
    Science: 52.54
    Commerce: 47.65
  International:
    Arts: 50.90
    Science: 69.51
    Commerce: 71.60


Year: 2020
  Vidya Mandir:
    Arts: 54.75
    Science: 66.10
    Commerce: 64.95
  St. Joseph:
    Arts: 54.03
    Science: 57.17
    Commerce: 56.20
  DPS:
    Arts: 57.62
    Science: 53.48
    Commerce: 54.75
  Birla HS:
    Arts: 72.22
    Science: 55.36
    Commerce: 60.05
  International:
    Arts: 53.08
    Science: 67.08
    Commerce: 69.50


Year: 2019
  Vidya Mandir:
    Arts: 54.75
    Science: 67.40
    Commerce: 48.15
  St. Joseph:
    Arts: 57.35
    Science: 61.49
    Commerce: 60.20
  DPS:
    Arts: 64.88
    Science: 56.83
    Commerce: 67.65
  Birla HS:
    Arts: 68.68
    Science: 58.40
    Commerce: 53.95
  International:
    Arts: 49.32
    Science: 72.36
    Commerce: 72.80


Year: 2021 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 7
    Good: 11
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 18
    Good: 2
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 14
    Good: 4
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 9
    Good: 8
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 10
    Very Good: 0


Year: 2020 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 7
    Good: 12
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 14
    Good: 6
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 19
    Good: 1
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 6
    Good: 10
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 11
    Good: 8
    Very Good: 0


Year: 2019 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 10
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 11
    Good: 9
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 12
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 5
    Good: 14
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 6
    Good: 14
    Very Good: 0


Best Schools by Year based on Good and Very Good categories:
Year 2021: Vidya Mandir with 11 students in Good and Very Good categories
Year 2020: Vidya Mandir with 12 students in Good and Very Good categories
Year 2019: Birla HS with 14 students in Good and Very Good categories

7.Which is the fastest-growing School in Bangalore (Overall and Streamwise)?

In [12]:


# Function to compute average marks per stream for a given dataset
def compute_stream_averages(data):
    arts_subjects = ['History', 'Geography', 'Civics']
    science_subjects = ['Mathematics', 'Physics', 'Chemistry', 'Biology']
    commerce_subjects = ['Computer Science']

    arts_avg = data[arts_subjects].mean(axis=1).mean() if all(sub in data for sub in arts_subjects) else None
    science_avg = data[science_subjects].mean(axis=1).mean() if all(sub in data for sub in science_subjects) else None
    commerce_avg = data[commerce_subjects].mean(axis=1).mean() if all(sub in data for sub in commerce_subjects) else None

    return {"Arts": arts_avg, "Science": science_avg, "Commerce": commerce_avg}

# Function to categorize students based on their average marks
def categorize_students(data):
    categories = {
        "Very Poor": (0, 20),
        "Poor": (21, 40),
        "Average": (41, 60),
        "Good": (61, 80),
        "Very Good": (81, 100)
    }

    avg_marks = data.mean(axis=1)
    category_counts = {category: 0 for category in categories}

    for mark in avg_marks:
        for category, (low, high) in categories.items():
            if low <= mark <= high:
                category_counts[category] += 1
                break

    return category_counts

# Aggregate results for all years
results = {}
category_results = {}

for year, path in file_paths.items():
    year_data = pd.ExcelFile(path)
    year_results = {}
    year_category_results = {}

    for sheet in year_data.sheet_names:
        school_data = pd.read_excel(year_data, sheet_name=sheet)
        year_results[sheet] = compute_stream_averages(school_data)
        year_category_results[sheet] = categorize_students(school_data.iloc[:, 2:])  # Exclude non-subject columns

    results[year] = year_results
    category_results[year] = year_category_results

# Print the results for each year
for year, schools in results.items():
    print(f"Year: {year}")
    for school, averages in schools.items():
        print(f"  {school}:")
        for stream, avg in averages.items():
            print(f"    {stream}: {avg:.2f}" if avg is not None else f"    {stream}: No data")
    print("\n")

# Print the category distribution for each year
for year, schools in category_results.items():
    print(f"Year: {year} - Category Distribution")
    for school, categories in schools.items():
        print(f"  {school}:")
        for category, count in categories.items():
            print(f"    {category}: {count}")
    print("\n")

# Determine the best school for each year based on Good and Very Good categories
best_schools = {}

for year, schools in category_results.items():
    best_school = None
    max_good_very_good = 0

    for school, categories in schools.items():
        good_very_good_total = categories.get("Good", 0) + categories.get("Very Good", 0)

        if good_very_good_total > max_good_very_good:
            best_school = school
            max_good_very_good = good_very_good_total

    best_schools[year] = (best_school, max_good_very_good)

# Print the best school for each year
print("Best Schools by Year based on Good and Very Good categories:")
for year, (school, count) in best_schools.items():
    print(f"Year {year}: {school} with {count} students in Good and Very Good categories")

# Determine the fastest-growing school (overall and streamwise)
def compute_growth(school_results):
    growth = {}

    for school in school_results["2019"].keys():
        growth[school] = {}

        for stream in ["Arts", "Science", "Commerce"]:
            try:
                start = school_results["2019"].get(school, {}).get(stream, 0)
                end = school_results["2021"].get(school, {}).get(stream, 0)

                if start is not None and end is not None:
                    growth[school][stream] = end - start
                else:
                    growth[school][stream] = None
            except KeyError:
                growth[school][stream] = None

        # Compute overall growth
        overall_start = sum(filter(None, [
            school_results["2019"].get(school, {}).get(stream, 0)
            for stream in ["Arts", "Science", "Commerce"]
        ]))

        overall_end = sum(filter(None, [
            school_results["2021"].get(school, {}).get(stream, 0)
            for stream in ["Arts", "Science", "Commerce"]
        ]))

        growth[school]["Overall"] = overall_end - overall_start

    return growth

school_growth = compute_growth(results)

# Identify the fastest-growing school (overall and streamwise)
fastest_growing = {}

for stream in ["Arts", "Science", "Commerce", "Overall"]:
    best_school = None
    max_growth = float("-inf")

    for school, growth in school_growth.items():
        if growth.get(stream, float("-inf")) > max_growth:
            best_school = school
            max_growth = growth[stream]

    fastest_growing[stream] = (best_school, max_growth)

# Print the fastest-growing schools
print("Fastest-Growing Schools (Overall and Streamwise):")
for stream, (school, growth) in fastest_growing.items():
    print(f"{stream}: {school} with a growth of {growth}")

Year: 2021
  Vidya Mandir:
    Arts: 55.07
    Science: 57.44
    Commerce: 76.00
  St. Joseph:
    Arts: 54.88
    Science: 54.05
    Commerce: 47.65
  DPS:
    Arts: 56.95
    Science: 55.36
    Commerce: 53.55
  Birla HS:
    Arts: 69.73
    Science: 52.54
    Commerce: 47.65
  International:
    Arts: 50.90
    Science: 69.51
    Commerce: 71.60


Year: 2020
  Vidya Mandir:
    Arts: 54.75
    Science: 66.10
    Commerce: 64.95
  St. Joseph:
    Arts: 54.03
    Science: 57.17
    Commerce: 56.20
  DPS:
    Arts: 57.62
    Science: 53.48
    Commerce: 54.75
  Birla HS:
    Arts: 72.22
    Science: 55.36
    Commerce: 60.05
  International:
    Arts: 53.08
    Science: 67.08
    Commerce: 69.50


Year: 2019
  Vidya Mandir:
    Arts: 54.75
    Science: 67.40
    Commerce: 48.15
  St. Joseph:
    Arts: 57.35
    Science: 61.49
    Commerce: 60.20
  DPS:
    Arts: 64.88
    Science: 56.83
    Commerce: 67.65
  Birla HS:
    Arts: 68.68
    Science: 58.40
    Commerce: 53.95
  International:
    Arts: 49.32
    Science: 72.36
    Commerce: 72.80


Year: 2021 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 7
    Good: 11
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 18
    Good: 2
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 14
    Good: 4
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 9
    Good: 8
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 10
    Very Good: 0


Year: 2020 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 7
    Good: 12
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 14
    Good: 6
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 19
    Good: 1
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 6
    Good: 10
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 11
    Good: 8
    Very Good: 0


Year: 2019 - Category Distribution
  Vidya Mandir:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 10
    Very Good: 0
  St. Joseph:
    Very Poor: 0
    Poor: 0
    Average: 11
    Good: 9
    Very Good: 0
  DPS:
    Very Poor: 0
    Poor: 0
    Average: 8
    Good: 12
    Very Good: 0
  Birla HS:
    Very Poor: 0
    Poor: 0
    Average: 5
    Good: 14
    Very Good: 0
  International:
    Very Poor: 0
    Poor: 0
    Average: 6
    Good: 14
    Very Good: 0


Best Schools by Year based on Good and Very Good categories:
Year 2021: Vidya Mandir with 11 students in Good and Very Good categories
Year 2020: Vidya Mandir with 12 students in Good and Very Good categories
Year 2019: Birla HS with 14 students in Good and Very Good categories
Fastest-Growing Schools (Overall and Streamwise):
Arts: International with a growth of 1.5833333333333428
Science: DPS with a growth of -1.4625000000000057
Commerce: Vidya Mandir with a growth of 27.85
Overall: Vidya Mandir with a growth of 18.20416666666665